# Generated by Django 4.1.6 on 2023-04-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0003_achievements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
    ]
