# Generated by Django 4.1.6 on 2023-04-06 11:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0005_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
    ]
