# Generated by Django 4.1.6 on 2023-04-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0006_alter_achievement_desc_alter_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
