# Generated by Django 4.1.6 on 2023-04-06 19:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkinfo',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
